Repository raj-sharma-01/Hacktoberfeast-2022, pull requests merged in 2022-10, with the labels that each got.

#1 Create My-first-commit
  My-first-commit
Labels: hacktoberfest-accepted, hacktoberfest-2022

#2 Create key-value pair
  key-value pair
Labels: hacktoberfest-accepted, hacktoberfest-2022

#3 Create css-file
  css-file
Labels: hacktoberfest-accepted, hacktoberfest-2022

#6 Create index-js-file
  index-js-file
Labels: good first issue, hacktoberfest-accepted, hacktoberfest-2022

#8 Create first-issue
  first-issue
Labels: good first issue, hacktoberfest-accepted, hacktoberfest-2022

#11 Create second_commit
  second_commit
Labels: hacktoberfest-accepted, hacktoberfest-2022

#10 Create linkedList
  linkedList
Labels: hacktoberfest-accepted, hacktoberfest-2022

#9 Create max_min.cpp
  max_min.cpp
Labels: hacktoberfest-accepted, hacktoberfest-2022

#12 insertion_sort.cpp
  Insertion_sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest-2022

#16 Create stringCode
  stringCode
Labels: hacktoberfest-accepted, hacktoberfest-2022

#15 merge sort
  merge sort
Labels: hacktoberfest-accepted, hacktoberfest-2022

#14 binary search
  binary search
Labels: hacktoberfest-accepted, hacktoberfest-2022

#13 selection_sort.cpp
  selection_sort.cpp
Labels: hacktoberfest-accepted

#19 Create select
  select
Labels: hacktoberfest-accepted, hacktoberfest-2022

#18 Create print
  print
Labels: hacktoberfest-accepted, hacktoberfest-2022

#17 Create swap
  swap
Labels: hacktoberfest-accepted, hacktoberfest-2022
